default avocado-a
timeout 1
prompt 0

label avocado-a
  kernel /Image
  fdt /r9a09g057h44-rzv2h-rdk.dtb
  initrd /avocado-image-initramfs-rzv2h-rdk.cpio.zst
  append console=ttySC0,115200 earlycon ro rootwait root=PARTUUID=3a126dc9-5f13-4c2a-a59d-9f28b42ecb42 rootfstype=erofs
